apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: qvorvbkxj-nodejs-gitops
  description: This is GitOps manifest for qvorvbkxj-nodejs   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: tssc/gitops=qvorvbkxj-nodejs
    backstage.io/kubernetes-id: qvorvbkxj-nodejs 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: qvorvbkxj-nodejs
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:qvorvbkxj-nodejs
